version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-frontend-assets:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build
workflows:
    build-and-deploy-staging:
      jobs:
        - build-frontend-assets:
            filters:
              branches:
                only: develop
    build-and-deploy-production:
      jobs:
        - build-frontend-assets:
            filters:
              branches:
                only: master